#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Apr 07 17:54:06 BST 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2025.2
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail
# simulate design
echo "xsim System_Top_wrapper_func_impl -key {Post-Implementation:sim_1:Functional:System_Top_wrapper} -tclbatch System_Top_wrapper.tcl -protoinst "protoinst_files/bd_a752.protoinst" -protoinst "protoinst_files/System_Top.protoinst" -log simulate.log"
xsim System_Top_wrapper_func_impl -key {Post-Implementation:sim_1:Functional:System_Top_wrapper} -tclbatch System_Top_wrapper.tcl -protoinst "protoinst_files/bd_a752.protoinst" -protoinst "protoinst_files/System_Top.protoinst" -log simulate.log

