# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gary/Individual_Project_System/Individual_Project_System.srcs/sources_1/bd/System_Top/ip/System_Top_BRAM_Wrapper_0_0/System_Top_BRAM_Wrapper_0_0.xci
# IP: The module: 'System_Top_BRAM_Wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gary/Individual_Project_System/Individual_Project_System.gen/sources_1/bd/System_Top/ip/System_Top_BRAM_Wrapper_0_0/src/PYNQ-Z2 v1.0.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_Top_BRAM_Wrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/gary/Individual_Project_System/Individual_Project_System.srcs/sources_1/bd/System_Top/ip/System_Top_BRAM_Wrapper_0_0/System_Top_BRAM_Wrapper_0_0.xci
# IP: The module: 'System_Top_BRAM_Wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gary/Individual_Project_System/Individual_Project_System.gen/sources_1/bd/System_Top/ip/System_Top_BRAM_Wrapper_0_0/src/PYNQ-Z2 v1.0.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_Top_BRAM_Wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
