# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/System_Top/System_Top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_Top || ORIG_REF_NAME==System_Top} -quiet] -quiet

# IP: bd/System_Top/ip/System_Top_processing_system7_0_0/System_Top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_Top_processing_system7_0_0 || ORIG_REF_NAME==System_Top_processing_system7_0_0} -quiet] -quiet

# IP: bd/System_Top/ip/System_Top_smartconnect_0_0/System_Top_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_Top_smartconnect_0_0 || ORIG_REF_NAME==System_Top_smartconnect_0_0} -quiet] -quiet

# IP: bd/System_Top/ip/System_Top_blk_mem_gen_0_0/System_Top_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_Top_blk_mem_gen_0_0 || ORIG_REF_NAME==System_Top_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/System_Top/ip/System_Top_axi_bram_ctrl_0_0/System_Top_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_Top_axi_bram_ctrl_0_0 || ORIG_REF_NAME==System_Top_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/System_Top/ip/System_Top_proc_sys_reset_0_0/System_Top_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_Top_proc_sys_reset_0_0 || ORIG_REF_NAME==System_Top_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/System_Top/ip/System_Top_Top_0_0/System_Top_Top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_Top_Top_0_0 || ORIG_REF_NAME==System_Top_Top_0_0} -quiet] -quiet

# IP: bd/System_Top/ip/System_Top_BRAM_Wrapper_0_0/System_Top_BRAM_Wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_Top_BRAM_Wrapper_0_0 || ORIG_REF_NAME==System_Top_BRAM_Wrapper_0_0} -quiet] -quiet

# IP: bd/System_Top/ip/System_Top_AXI_ArrayProc_0_0/System_Top_AXI_ArrayProc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==System_Top_AXI_ArrayProc_0_0 || ORIG_REF_NAME==System_Top_AXI_ArrayProc_0_0} -quiet] -quiet

# XDC: /home/gary/Individual_Project_System/Individual_Project_System.gen/sources_1/bd/System_Top/System_Top_ooc.xdc
